# Generated by Django 5.2.17 on 2026-09-21 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(message='Введите номер в международном формате: +79991234567, без пробелов и скобок.', regex='\\A\\+[1-9][0-9]{7,14}\\Z')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
