# Generated by Django 5.2.17 on 2026-09-22 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Подтверждаемый email')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Хеш кода')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Количество неверных попыток')),
                ('last_requested_at', models.DateTimeField(verbose_name='Последний запрос кода')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подтверждение email',
                'verbose_name_plural': 'Подтверждения email',
            },
        ),
    ]
